<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlg8hmg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlg8hmg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUlg8hmg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUlg8hmg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUlg8hmg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ulg8hmg',
    'container.build_id' => 'c8fc5ced',
    'container.build_time' => 1561706065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlg8hmg');
